fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [-b, main]
  - repo: local
    hooks:
      - id: mix-format
        name: "elixir: mix format"
        entry: mix format --check-formatted
        language: system
        files: \.ex*$
      - id: mix-compile
        name: "elixir: mix compile"
        entry: mix compile --force --warnings-as-errors
        language: system
        pass_filenames: false
        files: \.ex$
      - id: mix-credo
        name: "elixir: mix credo"
        entry: mix credo
        language: system
        pass_filenames: false
        files: \.ex*$
