version: "3"
services:
  miser:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/credentials.json
    volumes:
      - type: bind
        source: ./credentials.json
        target: /config/credentials.json
      - type: bind
        source: ./config.yml
        target: /config/config.yml
    ports:
      - "9090:9090"
