version: "3"
services:
  miser:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/credentials.json
    volumes:
      - ${PWD}/credentials.json:/config/credentials.json
      - ${PWD}/config.yml:/config/config.yml
    ports:
      - "9090:9090"
