version: "3"
services:
  cloud_monitoring_exporter:
    container_name: "cloud_monitoring_exporter"
    image: "massdrivercloud/cloud_monitoring_exporter:latest"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/credentials.json
    volumes:
      - type: bind
        source: ./credentials.json
        target: /config/credentials.json
      - type: bind
        source: ./config.yml
        target: /config/config.yml
    ports:
      - "9090:9090"
