name: Push Image
on:
  push:
    branches: [main]

jobs:
  image_push:
    name: Push Image
    runs-on: ubuntu-latest
    env:
      MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
      MASSDRIVER_ORG_ID: ${{ vars.MASSDRIVER_ORG_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions/setup@v3.1
      - name: Push Image
        uses: massdriver-cloud/actions/image_push@v3.1
        with:
          namespace: 'andreas-test'
          image-name: 'miser'
          artifact: ${{ vars.MASSDRIVER_ARTIFACT_ID }}
          region: 'us-west-2'
